// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bonnie_agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBonnieAgent = `-- name: CreateBonnieAgent :one
INSERT INTO kitt_bonnie_agents (name, url, token, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, url, token, status, last_seen_at, created_at, updated_at
`

type CreateBonnieAgentParams struct {
	Name   string `json:"name"`
	Url    string `json:"url"`
	Token  string `json:"token"`
	Status string `json:"status"`
}

func (q *Queries) CreateBonnieAgent(ctx context.Context, arg CreateBonnieAgentParams) (KittBonnieAgent, error) {
	row := q.db.QueryRow(ctx, createBonnieAgent,
		arg.Name,
		arg.Url,
		arg.Token,
		arg.Status,
	)
	var i KittBonnieAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBonnieAgent = `-- name: DeleteBonnieAgent :exec
DELETE FROM kitt_bonnie_agents WHERE id = $1
`

func (q *Queries) DeleteBonnieAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBonnieAgent, id)
	return err
}

const getBonnieAgent = `-- name: GetBonnieAgent :one
SELECT id, name, url, token, status, last_seen_at, created_at, updated_at FROM kitt_bonnie_agents WHERE id = $1
`

func (q *Queries) GetBonnieAgent(ctx context.Context, id pgtype.UUID) (KittBonnieAgent, error) {
	row := q.db.QueryRow(ctx, getBonnieAgent, id)
	var i KittBonnieAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBonnieAgentByName = `-- name: GetBonnieAgentByName :one
SELECT id, name, url, token, status, last_seen_at, created_at, updated_at FROM kitt_bonnie_agents WHERE name = $1
`

func (q *Queries) GetBonnieAgentByName(ctx context.Context, name string) (KittBonnieAgent, error) {
	row := q.db.QueryRow(ctx, getBonnieAgentByName, name)
	var i KittBonnieAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBonnieAgents = `-- name: ListBonnieAgents :many
SELECT id, name, url, token, status, last_seen_at, created_at, updated_at FROM kitt_bonnie_agents ORDER BY name
`

func (q *Queries) ListBonnieAgents(ctx context.Context) ([]KittBonnieAgent, error) {
	rows, err := q.db.Query(ctx, listBonnieAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KittBonnieAgent{}
	for rows.Next() {
		var i KittBonnieAgent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Token,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBonnieAgent = `-- name: UpdateBonnieAgent :one
UPDATE kitt_bonnie_agents
SET name = $2, url = $3, token = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, url, token, status, last_seen_at, created_at, updated_at
`

type UpdateBonnieAgentParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Url   string      `json:"url"`
	Token string      `json:"token"`
}

func (q *Queries) UpdateBonnieAgent(ctx context.Context, arg UpdateBonnieAgentParams) (KittBonnieAgent, error) {
	row := q.db.QueryRow(ctx, updateBonnieAgent,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Token,
	)
	var i KittBonnieAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBonnieAgentStatus = `-- name: UpdateBonnieAgentStatus :exec
UPDATE kitt_bonnie_agents
SET status = $2, last_seen_at = $3, updated_at = now()
WHERE id = $1
`

type UpdateBonnieAgentStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpdateBonnieAgentStatus(ctx context.Context, arg UpdateBonnieAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateBonnieAgentStatus, arg.ID, arg.Status, arg.LastSeenAt)
	return err
}
