// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCampaignRuns = `-- name: CountCampaignRuns :one
SELECT COUNT(*) FROM campaign_runs WHERE campaign_id = $1
`

func (q *Queries) CountCampaignRuns(ctx context.Context, campaignID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignRuns, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, description, config, cron_expr, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, config, cron_expr, enabled, created_at, updated_at
`

type CreateCampaignParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Config      []byte `json:"config"`
	CronExpr    string `json:"cron_expr"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.CronExpr,
		arg.Enabled,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, description, config, cron_expr, enabled, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByName = `-- name: GetCampaignByName :one
SELECT id, name, description, config, cron_expr, enabled, created_at, updated_at FROM campaigns WHERE name = $1
`

func (q *Queries) GetCampaignByName(ctx context.Context, name string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByName, name)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignRuns = `-- name: ListCampaignRuns :many
SELECT campaign_id, run_id, scheduled_at
FROM campaign_runs
WHERE campaign_id = $1
ORDER BY scheduled_at DESC
`

func (q *Queries) ListCampaignRuns(ctx context.Context, campaignID pgtype.UUID) ([]CampaignRun, error) {
	rows, err := q.db.Query(ctx, listCampaignRuns, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignRun{}
	for rows.Next() {
		var i CampaignRun
		if err := rows.Scan(&i.CampaignID, &i.RunID, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, description, config, cron_expr, enabled, created_at, updated_at FROM campaigns ORDER BY name
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.CronExpr,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET description = $2, config = $3, cron_expr = $4, enabled = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, config, cron_expr, enabled, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	Config      []byte      `json:"config"`
	CronExpr    string      `json:"cron_expr"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Description,
		arg.Config,
		arg.CronExpr,
		arg.Enabled,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignSchedule = `-- name: UpdateCampaignSchedule :one
UPDATE campaigns
SET cron_expr = $2, enabled = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, description, config, cron_expr, enabled, created_at, updated_at
`

type UpdateCampaignScheduleParams struct {
	ID       pgtype.UUID `json:"id"`
	CronExpr string      `json:"cron_expr"`
	Enabled  bool        `json:"enabled"`
}

func (q *Queries) UpdateCampaignSchedule(ctx context.Context, arg UpdateCampaignScheduleParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignSchedule, arg.ID, arg.CronExpr, arg.Enabled)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.CronExpr,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
