// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: engine_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEngineProfile = `-- name: CreateEngineProfile :one
INSERT INTO engine_profiles (
    name, engine, description, build_config, runtime_config, is_default
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, engine, description, build_config, runtime_config, is_default, created_at, updated_at
`

type CreateEngineProfileParams struct {
	Name          string `json:"name"`
	Engine        string `json:"engine"`
	Description   string `json:"description"`
	BuildConfig   []byte `json:"build_config"`
	RuntimeConfig []byte `json:"runtime_config"`
	IsDefault     bool   `json:"is_default"`
}

func (q *Queries) CreateEngineProfile(ctx context.Context, arg CreateEngineProfileParams) (EngineProfile, error) {
	row := q.db.QueryRow(ctx, createEngineProfile,
		arg.Name,
		arg.Engine,
		arg.Description,
		arg.BuildConfig,
		arg.RuntimeConfig,
		arg.IsDefault,
	)
	var i EngineProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Description,
		&i.BuildConfig,
		&i.RuntimeConfig,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEngineProfile = `-- name: DeleteEngineProfile :exec
DELETE FROM engine_profiles WHERE id = $1
`

func (q *Queries) DeleteEngineProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEngineProfile, id)
	return err
}

const getEngineProfile = `-- name: GetEngineProfile :one
SELECT id, name, engine, description, build_config, runtime_config, is_default, created_at, updated_at FROM engine_profiles WHERE id = $1
`

func (q *Queries) GetEngineProfile(ctx context.Context, id pgtype.UUID) (EngineProfile, error) {
	row := q.db.QueryRow(ctx, getEngineProfile, id)
	var i EngineProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Description,
		&i.BuildConfig,
		&i.RuntimeConfig,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEngineProfiles = `-- name: ListEngineProfiles :many
SELECT id, name, engine, description, build_config, runtime_config, is_default, created_at, updated_at FROM engine_profiles ORDER BY engine, name
`

func (q *Queries) ListEngineProfiles(ctx context.Context) ([]EngineProfile, error) {
	rows, err := q.db.Query(ctx, listEngineProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EngineProfile{}
	for rows.Next() {
		var i EngineProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Description,
			&i.BuildConfig,
			&i.RuntimeConfig,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngineProfilesByEngine = `-- name: ListEngineProfilesByEngine :many
SELECT id, name, engine, description, build_config, runtime_config, is_default, created_at, updated_at FROM engine_profiles WHERE engine = $1 ORDER BY name
`

func (q *Queries) ListEngineProfilesByEngine(ctx context.Context, engine string) ([]EngineProfile, error) {
	rows, err := q.db.Query(ctx, listEngineProfilesByEngine, engine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EngineProfile{}
	for rows.Next() {
		var i EngineProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Description,
			&i.BuildConfig,
			&i.RuntimeConfig,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEngineProfile = `-- name: UpdateEngineProfile :one
UPDATE engine_profiles
SET name = $2, description = $3, build_config = $4,
    runtime_config = $5, is_default = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, engine, description, build_config, runtime_config, is_default, created_at, updated_at
`

type UpdateEngineProfileParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	BuildConfig   []byte      `json:"build_config"`
	RuntimeConfig []byte      `json:"runtime_config"`
	IsDefault     bool        `json:"is_default"`
}

func (q *Queries) UpdateEngineProfile(ctx context.Context, arg UpdateEngineProfileParams) (EngineProfile, error) {
	row := q.db.QueryRow(ctx, updateEngineProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BuildConfig,
		arg.RuntimeConfig,
		arg.IsDefault,
	)
	var i EngineProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Description,
		&i.BuildConfig,
		&i.RuntimeConfig,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
