// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hardware.sql

package sqlc

import (
	"context"
)

const createHardware = `-- name: CreateHardware :one
INSERT INTO hardware (
    fingerprint, gpu, cpu, ram_gb, storage, cuda_version,
    driver_version, os, environment, details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, fingerprint, gpu, cpu, ram_gb, storage, cuda_version,
          driver_version, os, environment, details, created_at
`

type CreateHardwareParams struct {
	Fingerprint   string `json:"fingerprint"`
	Gpu           string `json:"gpu"`
	Cpu           string `json:"cpu"`
	RamGb         int32  `json:"ram_gb"`
	Storage       string `json:"storage"`
	CudaVersion   string `json:"cuda_version"`
	DriverVersion string `json:"driver_version"`
	Os            string `json:"os"`
	Environment   string `json:"environment"`
	Details       []byte `json:"details"`
}

func (q *Queries) CreateHardware(ctx context.Context, arg CreateHardwareParams) (Hardware, error) {
	row := q.db.QueryRow(ctx, createHardware,
		arg.Fingerprint,
		arg.Gpu,
		arg.Cpu,
		arg.RamGb,
		arg.Storage,
		arg.CudaVersion,
		arg.DriverVersion,
		arg.Os,
		arg.Environment,
		arg.Details,
	)
	var i Hardware
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Gpu,
		&i.Cpu,
		&i.RamGb,
		&i.Storage,
		&i.CudaVersion,
		&i.DriverVersion,
		&i.Os,
		&i.Environment,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getHardwareByFingerprint = `-- name: GetHardwareByFingerprint :one

SELECT id, fingerprint, gpu, cpu, ram_gb, storage, cuda_version,
       driver_version, os, environment, details, created_at
FROM hardware
WHERE fingerprint = $1
`

// Seed query set — exercises sqlc codegen so the repo stays buildable
// before domain queries arrive in later PRs. Replace/extend these as
// the storage layer grows.
func (q *Queries) GetHardwareByFingerprint(ctx context.Context, fingerprint string) (Hardware, error) {
	row := q.db.QueryRow(ctx, getHardwareByFingerprint, fingerprint)
	var i Hardware
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Gpu,
		&i.Cpu,
		&i.RamGb,
		&i.Storage,
		&i.CudaVersion,
		&i.DriverVersion,
		&i.Os,
		&i.Environment,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listHardware = `-- name: ListHardware :many
SELECT id, fingerprint, gpu, cpu, ram_gb, storage, cuda_version,
       driver_version, os, environment, details, created_at
FROM hardware
ORDER BY created_at DESC
`

func (q *Queries) ListHardware(ctx context.Context) ([]Hardware, error) {
	rows, err := q.db.Query(ctx, listHardware)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hardware{}
	for rows.Next() {
		var i Hardware
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Gpu,
			&i.Cpu,
			&i.RamGb,
			&i.Storage,
			&i.CudaVersion,
			&i.DriverVersion,
			&i.Os,
			&i.Environment,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
