// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Benchmark struct {
	ID         pgtype.UUID        `json:"id"`
	RunID      pgtype.UUID        `json:"run_id"`
	Benchmark  string             `json:"benchmark"`
	Status     string             `json:"status"`
	Score      pgtype.Float8      `json:"score"`
	DurationMs pgtype.Int8        `json:"duration_ms"`
	RawJson    []byte             `json:"raw_json"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BenchmarkRegistry struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	Category    string             `json:"category"`
	Description string             `json:"description"`
	Source      string             `json:"source"`
	Config      []byte             `json:"config"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Campaign struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Config      []byte             `json:"config"`
	CronExpr    string             `json:"cron_expr"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CampaignRun struct {
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	RunID       pgtype.UUID        `json:"run_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

type EngineProfile struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Engine        string             `json:"engine"`
	Description   string             `json:"description"`
	BuildConfig   []byte             `json:"build_config"`
	RuntimeConfig []byte             `json:"runtime_config"`
	IsDefault     bool               `json:"is_default"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Hardware struct {
	ID            pgtype.UUID        `json:"id"`
	Fingerprint   string             `json:"fingerprint"`
	Gpu           string             `json:"gpu"`
	Cpu           string             `json:"cpu"`
	RamGb         int32              `json:"ram_gb"`
	Storage       string             `json:"storage"`
	CudaVersion   string             `json:"cuda_version"`
	DriverVersion string             `json:"driver_version"`
	Os            string             `json:"os"`
	Environment   string             `json:"environment"`
	Details       []byte             `json:"details"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type KittBonnieAgent struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Token      string             `json:"token"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Metric struct {
	ID          int64              `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	BenchmarkID pgtype.UUID        `json:"benchmark_id"`
	Name        string             `json:"name"`
	Value       float64            `json:"value"`
	Unit        string             `json:"unit"`
	RecordedAt  pgtype.Timestamptz `json:"recorded_at"`
}

type NotificationConfig struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Channel   string             `json:"channel"`
	Target    string             `json:"target"`
	Config    []byte             `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Run struct {
	ID              pgtype.UUID        `json:"id"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	HardwareID      pgtype.UUID        `json:"hardware_id"`
	Model           string             `json:"model"`
	Engine          string             `json:"engine"`
	EngineProfileID pgtype.UUID        `json:"engine_profile_id"`
	Status          string             `json:"status"`
	Error           string             `json:"error"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
