// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBenchmarkResult = `-- name: CreateBenchmarkResult :one
INSERT INTO benchmarks (
    run_id, benchmark, status, score, duration_ms, raw_json,
    started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, run_id, benchmark, status, score, duration_ms, raw_json, started_at, finished_at, created_at
`

type CreateBenchmarkResultParams struct {
	RunID      pgtype.UUID        `json:"run_id"`
	Benchmark  string             `json:"benchmark"`
	Status     string             `json:"status"`
	Score      pgtype.Float8      `json:"score"`
	DurationMs pgtype.Int8        `json:"duration_ms"`
	RawJson    []byte             `json:"raw_json"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateBenchmarkResult(ctx context.Context, arg CreateBenchmarkResultParams) (Benchmark, error) {
	row := q.db.QueryRow(ctx, createBenchmarkResult,
		arg.RunID,
		arg.Benchmark,
		arg.Status,
		arg.Score,
		arg.DurationMs,
		arg.RawJson,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Benchmark
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Benchmark,
		&i.Status,
		&i.Score,
		&i.DurationMs,
		&i.RawJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMetric = `-- name: CreateMetric :one
INSERT INTO metrics (run_id, benchmark_id, name, value, unit)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, benchmark_id, name, value, unit, recorded_at
`

type CreateMetricParams struct {
	RunID       pgtype.UUID `json:"run_id"`
	BenchmarkID pgtype.UUID `json:"benchmark_id"`
	Name        string      `json:"name"`
	Value       float64     `json:"value"`
	Unit        string      `json:"unit"`
}

func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) (Metric, error) {
	row := q.db.QueryRow(ctx, createMetric,
		arg.RunID,
		arg.BenchmarkID,
		arg.Name,
		arg.Value,
		arg.Unit,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.BenchmarkID,
		&i.Name,
		&i.Value,
		&i.Unit,
		&i.RecordedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    campaign_id, agent_id, hardware_id, model, engine,
    engine_profile_id, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, campaign_id, agent_id, hardware_id, model, engine, engine_profile_id, status, error, started_at, finished_at, created_at, updated_at
`

type CreateRunParams struct {
	CampaignID      pgtype.UUID `json:"campaign_id"`
	AgentID         pgtype.UUID `json:"agent_id"`
	HardwareID      pgtype.UUID `json:"hardware_id"`
	Model           string      `json:"model"`
	Engine          string      `json:"engine"`
	EngineProfileID pgtype.UUID `json:"engine_profile_id"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.CampaignID,
		arg.AgentID,
		arg.HardwareID,
		arg.Model,
		arg.Engine,
		arg.EngineProfileID,
		arg.Status,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AgentID,
		&i.HardwareID,
		&i.Model,
		&i.Engine,
		&i.EngineProfileID,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, campaign_id, agent_id, hardware_id, model, engine, engine_profile_id, status, error, started_at, finished_at, created_at, updated_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AgentID,
		&i.HardwareID,
		&i.Model,
		&i.Engine,
		&i.EngineProfileID,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBenchmarksForRun = `-- name: ListBenchmarksForRun :many
SELECT id, run_id, benchmark, status, score, duration_ms, raw_json, started_at, finished_at, created_at FROM benchmarks WHERE run_id = $1 ORDER BY benchmark
`

func (q *Queries) ListBenchmarksForRun(ctx context.Context, runID pgtype.UUID) ([]Benchmark, error) {
	rows, err := q.db.Query(ctx, listBenchmarksForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Benchmark{}
	for rows.Next() {
		var i Benchmark
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Benchmark,
			&i.Status,
			&i.Score,
			&i.DurationMs,
			&i.RawJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricsForRun = `-- name: ListMetricsForRun :many
SELECT id, run_id, benchmark_id, name, value, unit, recorded_at FROM metrics WHERE run_id = $1 ORDER BY recorded_at
`

func (q *Queries) ListMetricsForRun(ctx context.Context, runID pgtype.UUID) ([]Metric, error) {
	rows, err := q.db.Query(ctx, listMetricsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Metric{}
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.BenchmarkID,
			&i.Name,
			&i.Value,
			&i.Unit,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, campaign_id, agent_id, hardware_id, model, engine, engine_profile_id, status, error, started_at, finished_at, created_at, updated_at FROM runs ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AgentID,
			&i.HardwareID,
			&i.Model,
			&i.Engine,
			&i.EngineProfileID,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByCampaign = `-- name: ListRunsByCampaign :many
SELECT id, campaign_id, agent_id, hardware_id, model, engine, engine_profile_id, status, error, started_at, finished_at, created_at, updated_at FROM runs WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AgentID,
			&i.HardwareID,
			&i.Model,
			&i.Engine,
			&i.EngineProfileID,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2, error = $3, started_at = $4, finished_at = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, agent_id, hardware_id, model, engine, engine_profile_id, status, error, started_at, finished_at, created_at, updated_at
`

type UpdateRunStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	Error      string             `json:"error"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AgentID,
		&i.HardwareID,
		&i.Model,
		&i.Engine,
		&i.EngineProfileID,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
